spring.application.name=tenant-management-owner-service

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/owner_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.flyway.enabled=false

spring.flyway.locations=classpath:db/migration

